version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0
    steps:
      - checkout
      - run:
          name: Maven Build
          command: mvn -B verify

  code-quality:
    docker:
      - image: jetbrains/qodana-jvm:2025.2
    steps:
      - checkout
      - run:
          name: Run Qodana Scan
          command: qodana scan --fail-threshold 1

workflows:
  main:
    jobs:
      - build
      - code-quality:
          requires:
            - build
