version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0
    steps:
      - checkout
      - run:
          name: Run Maven Tests
          command: mvn -B test
      - run:
          name: Maven Build
          command: mvn -B verify

  qodana:
    docker:
      - image: jetbrains/qodana-jvm:latest
    steps:
      - checkout
      - run:
          name: Run Qodana Static Analysis
          command: qodana scan --fail-threshold 1

workflows:
  pipeline:
    jobs:
      - build
      - qodana:
          requires:
            - build
